@CollegeStudentXtramile.Server_HostAddress = http://localhost:5181

GET {{CollegeStudentXtramile.Server_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{CollegeStudentXtramile.Server_HostAddress}}/api/v1/students
Accept: application/json

###